version: 0.2

phases:
  install:
    commands:
      - echo "Starting the install phase..."
  pre_build:
    commands:
      - echo "Starting the pre-build phase..."
  build:
    commands:
      - echo "Hello, World!"
  post_build:
    commands:
      - echo "Build phase complete. Exiting..."
