version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing container scanning tools..."
      - pip install --upgrade pip
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
  pre_build:
    commands:
      - echo "Building Docker Container"
      - docker build -t $IMAGE_REPO_NAME:latest .
  build:
    commands:
      - echo "Scanning container for vulnerabilities with Trivy..."
      # Fail the build on HIGH and CRITICAL vulnerabilities
      #- ./bin/trivy image --severity HIGH,CRITICAL --exit-code 1 $IMAGE_REPO_NAME:latest
      - ./bin/trivy image --severity HIGH,CRITICAL --exit-code 0 $IMAGE_REPO_NAME:latest
  post_build:
    commands:
      - echo "Container Scanning completed."

artifacts:
  files:
    - "**/*"
  discard-paths: yes
  